name: apicompat-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Ubuntu_x64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['Release', 'Debug']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build -c ${{ matrix.configuration }}
      - name: Test
        run: dotnet test --no-build --verbosity normal -c ${{ matrix.configuration }}
