name: apicompat-ci

on: [push, pull_request]

jobs:
  build:
  strategy:
    matrix:
      configuration: ['Release', 'Debug']
  name: Ubuntu x64 ${{ matrix.configuration }}
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c ${{ matrix.configuration }}
